### PR TITLE
adding r-stringi to conda environment

### PR DESCRIPTION
**Pull request by shukwong**
stringi seems to be required by construct.model.matrix

### CODE REVIEW

**Comment by ghost** [comment]
@shukwong  fascinating... r-stringi isn't installed implicitly? it seems to be installed in my `plco-analysis` env. adding it is fine w/me, but i'm curious why i'm pulling in a copy and you're not... spells trouble for future issues

**Comment by shukwong** [comment]
not sure why, but now that it's in I am getting a related issue with stringi - trying to update the package and see if it solves the issue...

**Comment by shukwong** [comment]
@cpalmer718 so I am getting the error related to stringi 
libicui18n.so.64: cannot open shared object file: No such file or directory
googling it lead me to doing a manual update.packages() with R and it seems to solve the issue. It's now updated to 1.5.3 from the conda version 1.4.3 but still not sure why it didn't work in the first place

**Comment by ghost** [comment]
@shukwong so this is a whole chain of dependencies. the first thing: the icu error is known and fixed by pinning icu=58.2 in environment.yaml. as for why it's an issue to begin with: my guess is that the update process you did there has risked breaking SAIGE, which is where a bunch of the R deps come from. 

you can proceed as-is for now, but keep an eye out for catastrophic package errors when running SAIGE. if it's broken, try rebuilding the environment from scratch with r-stringr and r-stringi in the environment, along with icu=58.2, and see if that resolves correctly.

i don't understand why r-stringi was absent for you to begin with, i've never had that happen (r-construct.model.matrix should pull it in correctly). i'll try rebuilding on my end and see if the r-construct.model.matrix version update i did this morning somehow broke it.

**Comment by ghost** [comment]
@shukwong nope, mamba is pulling in r-stringi on its own. i am absolutely flummoxed as to why you didn't end up with r-stringi. is your ~/.condarc different than:

channels:
  - https://raw.githubusercontent.com/NCI-CGR/conda-cgr/default/conda-cgr
  - r
  - bioconda
  - conda-forge
  - defaults

**Comment by shukwong** [comment]
@cpalmer718 Mine doesn't have r! I think that might be why. Let me rebuild and try it out. Sorry about this could you revert the pull request.  Mine currently looks like:
channels:
  - https://raw.githubusercontent.com/NCI-CGR/conda-cgr/default/conda-cgr
  - conda-forge
  - bioconda
  - defaults

**Comment by ghost** [comment]
Ah! That'll do it.

I have a question in fact: I feel like... when I look at this repository, it doesn't scream "HERE'S WHERE MY DOCS ARE" lol. do you have any idea how I might lay things out differently to really encourage people to click on the readthedocs link? because there's a section about conda channels in there, but I also feel like... if I just looked at the repo, I'd not necessarily click on it!

maybe I should remove more of the README.md content, to make it clearer that that's not really where people should be looking?

**Comment by ghost** [comment]
ok all better, except we're technically on alpha.6 now lol. there are still some documentation upgrades in there

**Comment by shukwong** [comment]
Thanks! 
I think README.md is good as it is, perhaps make it more obvious by instead of "here", use "readthedocs", I would probably be more likely clicking on that :)

**Comment by ghost** [comment]
excellent idea, will do.

**Pull request merged**
